### ISSUE TITLE
Bower or it didn't happen:)

### ISSUE THREAD

**Issue by larvanitis** [tzusman/custom-font-icons#1]
Thanks for having this great idea!

Could you please add _bower_ and/or _npm_ files to the project?

**Comment by tzusman** [comment]
Hi Leonidas, thanks for the feedback :]

Could you please check my bower.json file and see if it's what you need?  I'm new to bower.

Thanks!

**Comment by larvanitis** [comment]
The bower.json file looks ok for now but I won't be able to test it until tomorow.

As a bonus have some food for thought:

- Project name: `custom-font-icons` is too generic. You might want to choose some _more brandable_ name to make it easier to find (SEO etc) - not sure if including _font awesome_ would be ok with the original owner but you can ask.
- Documentation: add step by step instructions to `README.md` for _Installation_, _Contribution_ etc.
- Project Structure: looking at what Font Awesome does, maybe keep fonts under `/fonts/`, styles under `/css/` etc.
- Versioning: is the project production ready? If not, it might be better to revert to `0.x.y` until it is. Also a must for getting listed to package repos (like bower and npm) is tagging along the way.


Anyways, thanks again for your time and work!

**Comment by tzusman** [comment]
I'm going to close this out.  See #4 for progress on build pipeline and distribution
