### ISSUE TITLE
Improve folder structure to match font-awesome

### ISSUE THREAD

**Issue by BenWoodford** [tzusman/custom-font-icons#2]
As this pack ties in so well with FA, it's only right that it also ties in well from a structural point of view. FA has a CSS folder and a Fonts folder, and references to the fonts are done as  "../fonts/fontfile.ext" rather than CFI's "./fontfile.ext". It seems fairly sensible to match the FA folder structure for ease of use, especially when using bower so you generally don't want to edit vendor files to change paths.

**Comment by CrashyBang** [comment]
I would love to see this implemented it makes sense to as most developers use some sort of build tool (grunt, gulp, webpack, etc...) and usually glob(**/*) font paths but in this case you also get all the css & bower files which is fine just a bit messy, would be happy to flick a PR through if you would like to implement?

**Comment by tzusman** [comment]
@CrashyBang If you'd like to create a PR I'd be happy to merge!

**Comment by tzusman** [comment]
@CrashyBang Merged!

I also added the source SVGs that I have, including some which were previously unreleased.  If you'd like to create a PR with a compile tool that just auto imports all the svgs into a font, that would be awesome!

**Comment by tzusman** [comment]
moving conversation on the build process to #4
